engine/routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('offline', function () {
//     return view('vendor.laravelpwa.offline');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

// require __DIR__ . '/auth.php';
Route::get('/', 'HomeController@index')->name('home');

//temporary
Route::get('detail/{slug}', 'ItemController@show');
Route::post('compare', 'CompareController@index');

Route::post('getsubtotal', 'ItemController@getSubTotal');
Route::get('filter', 'FilterController@getFilter');


Route::prefix('member')->group(function () {
    Route::get('login/email', 'LoginController@showLoginEmail')->name('login.email');
    Route::post('login/email', 'LoginController@loginEmail')->name('login.email');
    Route::get('login/wa', 'LoginController@loginWa')->name('login.wa');
    Route::post('login/wa', 'LoginController@loginWaOtp')->name('login.wa');
    Route::get('login/wa-verif/{phone}', 'LoginController@loginWaVerif')->name('login.wa-verif');
    Route::post('login/wa-verif', 'LoginController@loginWaVerifOtp')->name('login.wa-verif');
    Route::post('login/sosmed', 'LoginController@loginWithSosmed');

    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('register', 'LoginController@showRegister')->name('register.email');
    Route::post('register', 'LoginController@register')->name('register.email');
    Route::get('verification', 'LoginController@verification')->name('register.verification');


    // Route::get('showlogin', 'LoginController@showLogin');
    // Route::get('showregister', 'LoginController@showRegister');
    // Route::post('register', 'LoginController@register');
    // Route::post('sendotplogin', 'LoginController@sendotp');subTotal

    Route::group(['middleware' => ['auth']], function () {
        Route::post('sendotp', 'Member\KeamananController@sendOtp');
        Route::post('verifyOtp', 'Member\KeamananController@verifyOtp');

        Route::resource('cart', 'Member\CartController');
        Route::post('cart/getsubtotal', 'Member\CartController@getSubTotal');
        Route::post('cart/updateqty', 'Member\CartController@updateQuantity');
        Route::resource('wishlist', 'Member\WishlistController');
        Route::resource('address', 'Member\AddressController');

        Route::resource('profile', 'Member\ProfileController');
        Route::resource('keamanan', 'Member\KeamananController');
    });
});
Route::get('{category}', 'ItemCategoryController@category');
Route::get('{category}/{sub_category}', 'ItemCategoryController@show'); //wuaaaaaaaaaa gelut dengan route yang lain wkwkwkkwk

engine/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="robots" content="noindex, nofollow">
        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        @laravelPWA
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{-- {{ $header }} --}}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{-- {{ $slot }} --}}
            </main>
        </div>
    </body>
</html>

engine/resources/views/layouts/auth-master.blade.php
<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login - Email</title>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- start:stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
        crossorigin="anonymous" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/awesome-bootstrap-checkbox/1.0.0-alpha.2/awesome-bootstrap-checkbox.min.css">
    <link rel="stylesheet" href="{{asset("assets/vendor/bootstrap/css/bootstrap.min.css")}}">
    <link rel="stylesheet" href="{{asset("assets/css/main.css")}}">
    @stack('css')
    <!-- end:/stylesheets -->
    @laravelPWA
</head>

<body>
    <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '216792006848050',
            cookie     : true,
            xfbml      : true,
            version    : 'v10.0'
          });

          FB.AppEvents.logPageView();

        };

        (function(d, s, id){
           var js, fjs = d.getElementsByTagName(s)[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement(s); js.id = id;
           js.src = "https://connect.facebook.net/en_US/sdk.js";
           fjs.parentNode.insertBefore(js, fjs);
         }(document, 'script', 'facebook-jssdk'));
    </script>
    <!-- start:header -->
    <header class="header header--other-page">
        <img src="{{asset("assets/images/logo-white.svg")}}" alt="Logo Agres ID">
    </header>
    <!-- end:/header -->

    @yield('content')

    <!-- start:footer -->
    <footer class="footer footer--other-page">
        <!-- start:footer copyright -->
        <div class="footer__copyright">
            <p>Copyright © 2021 AGRES. All Rights Reserved</p>
        </div>
        <!-- end:/footer copyright -->
    </footer>
    <!-- end:/footer -->

    <!-- start:javascripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{{asset("assets/vendor/bootstrap/js/bootstrap.min.js")}}"></script>
    <script src="{{asset("assets/js/style.js")}}"></script>
    <!-- end:/javascripts -->


    <!-- The core Firebase JS SDK is always required and must be listed first -->
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-app.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
   https://firebase.google.com/docs/web/setup#available-libraries -->
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-analytics.js"></script>

    <script>
        // Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
var firebaseConfig = {
      apiKey: "AIzaSyBKy9xFR6x-L_ufxg9nRsev1VtVyO3fu9U",
      authDomain: "web-app-agres.firebaseapp.com",
      projectId: "web-app-agres",
      storageBucket: "web-app-agres.appspot.com",
      messagingSenderId: "594855414554",
      appId: "1:594855414554:web:8e904d2d89d94268e83aa3",
      measurementId: "G-C9VPBELP6C"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
    </script>
    <!-- Add Firebase products that you want to use -->
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-firestore.js"></script>

    <script>
        $("#google_signin").click(function(){

            var provider = new firebase.auth.GoogleAuthProvider();
            firebase.auth().languageCode = 'en';
            firebase.auth()
            .signInWithPopup(provider)
            .then((result) => {
                /** @type {firebase.auth.OAuthCredential} */
                var credential = result.credential;
                // This gives you a Google Access Token. You can use it to access the Google API.
                var token = credential.accessToken;
                // The signed-in user info.
                var email = result.user.email;
                var name = result.user.displayName;
                var phone = result.user.phoneNumber;
                var image = result.user.photoURL;
                $.ajax({
                        url: "{{url('/')}}/member/login/sosmed",
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        method: 'post',
                        data: {token:token, email:email, name:name, phone:phone, image:image},
                        success: function (data){
                            if (data == true){
                                window.location.replace("{{url('/')}}")
                            } else {
                                window.location.refresh()
                            }
                        }
                    })
            }).catch((error) => {
                // Handle Errors here.
                var errorCode = error.code;
                var errorMessage = error.message;
                if (errorCode === 'auth/account-exists-with-different-credential'){
                    var email = error.email
                    var token = error.credential.accessToken
                    $.ajax({
                            url: "{{url('/')}}/member/login/sosmed",
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            method: 'post',
                            data: {token:token, email:email},
                            success: function (data){
                                if (data == true){
                                    window.location.replace("{{url('/')}}")
                                } else {
                                    window.location.refresh()
                                }
                            }
                        })
                }
            });

        });

        $("#facebook_signin").click(function(){
            var provider = new firebase.auth.FacebookAuthProvider();
            firebase.auth().useDeviceLanguage();
            // provider.setCustomParameters({
            //     'display': 'popup'
            // });
            firebase
            .auth()
            .signInWithPopup(provider)
            .then((result) => {
                /** @type {firebase.auth.OAuthCredential} */
                console.dir(result);

                var credential = result.credential;
                // The signed-in user info.
                var email = result.user.email;
                // This gives you a Facebook Access Token. You can use it to access the Facebook API.
                var accessToken = credential.accessToken;
                var name = result.user.displayName;
                var phone = result.user.phoneNumber;
                var image = result.user.photoURL;
                $.ajax({
                        url: "{{url('/')}}/member/login/sosmed",
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        method: 'post',
                        data: {token:accessToken, email:email, name:name, phone:phone, image:image},
                        success: function (data){
                            if (data == true){
                                window.location.replace("{{url('/')}}")
                            } else {
                                window.location.refresh()
                            }
                        }
                    })
            })
            .catch((error) => {
                console.log(error)

                // Handle Errors here.
                var errorCode = error.code;
                var errorMessage = error.message;
                if (errorCode === 'auth/account-exists-with-different-credential'){
                    var email = error.email
                    var token = error.credential.accessToken
                    $.ajax({
                            url: "{{url('/')}}/member/login/sosmed",
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            method: 'post',
                            data: {token:token, email:email},
                            success: function (data){
                                if (data == true){
                                    window.location.replace("{{url('/')}}")
                                } else {
                                    window.location.refresh()
                                }
                            }
                        })
                }
            });
        })

    </script>

    @stack('js')
</body>

</html>

engine/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="robots" content="noindex, nofollow">
        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        @laravelPWA
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

engine/resources/views/layouts/header.blade.php
<!-- start:header -->
<header class="header">
    <!-- start:header top -->
    <div class="header__top">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">TENTANG AGRES.ID</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">KONTAK</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">MEMBER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">KONFIRMASI PEMBAYARAN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">ARTIKEL</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">PROMO</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            <svg width="21" height="19" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g clip-path="url(#clip0)">
                                    <path
                                        d="M10.5 19l-.196-.066C2.698 16.385-.004 10.718-.004 6.639-.004 2.919 2.316 0 5.276 0h.005a7.14 7.14 0 012.843.62c.896.4 1.703.98 2.371 1.705A7.229 7.229 0 0112.867.619C13.763.22 14.73.01 15.709 0h.004c2.962 0 5.282 2.916 5.282 6.639 0 4.079-2.698 9.746-10.303 12.295L10.5 19zM5.278 1.273c-2.257 0-4.024 2.359-4.024 5.367 0 3.62 2.426 8.655 9.246 11.02 6.82-2.365 9.246-7.4 9.246-11.02 0-3.008-1.768-5.365-4.025-5.367-.81.008-1.61.184-2.352.516a5.97 5.97 0 00-1.96 1.416 1.192 1.192 0 01-.909.426 1.177 1.177 0 01-.908-.426 5.971 5.971 0 00-1.961-1.417 5.896 5.896 0 00-2.353-.515z"
                                        fill="#333" />
                                </g>
                                <defs>
                                    <clipPath id="clip0">
                                        <path fill="#fff" d="M0 0h21v19H0z" />
                                    </clipPath>
                                </defs>
                            </svg>
                            <span class="ml-1">WISHLIST @if(Auth::check()) ({{count(Auth::user()->wishlist)}}) @else() (0) @endif</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <svg width="21" height="19" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g clip-path="url(#clip0)">
                                    <path
                                        d="M20.88 3.623a.667.667 0 00-.229-.197.696.696 0 00-.296-.08L7.33 2.809a.7.7 0 00-.491.167.65.65 0 00-.221.452.625.625 0 00.18.47.674.674 0 00.474.206l12.145.503-2.389 7.162H6.402L4.48 1.718a.638.638 0 00-.143-.294.674.674 0 00-.273-.192L.92.045a.698.698 0 00-.505.022.659.659 0 00-.347.353.624.624 0 00.006.485.66.66 0 00.356.345l2.79 1.057 1.96 10.225c.028.15.11.284.231.381a.69.69 0 00.432.15h.325l-.744 1.977a.519.519 0 00.068.492.579.579 0 00.458.23h.52c-.261.279-.433.625-.494.996-.061.37-.01.75.15 1.094.159.343.418.635.746.84.327.204.71.313 1.1.313.391 0 .774-.109 1.102-.314.327-.204.586-.496.745-.839.16-.343.211-.723.15-1.094a1.914 1.914 0 00-.494-.997h4.407c-.262.28-.433.626-.495.997-.06.37-.008.75.15 1.094.16.343.418.635.746.84.328.204.71.313 1.101.313s.773-.109 1.101-.314c.328-.204.587-.496.746-.839.159-.343.211-.723.15-1.094a1.913 1.913 0 00-.494-.997h.63a.572.572 0 00.396-.157.528.528 0 00.164-.381.528.528 0 00-.164-.38.572.572 0 00-.396-.159H6.75l.606-1.619h10.162a.693.693 0 00.397-.124.65.65 0 00.245-.326l2.807-8.42a.628.628 0 00-.088-.568v-.004zM7.974 17.921a.924.924 0 01-.5-.146.872.872 0 01-.33-.387.832.832 0 01-.051-.5.854.854 0 01.246-.441.931.931 0 01.979-.187.891.891 0 01.402.318.84.84 0 01-.112 1.09.918.918 0 01-.634.253zm7.411 0a.924.924 0 01-.499-.146.872.872 0 01-.33-.387.832.832 0 01-.051-.5.853.853 0 01.245-.441.931.931 0 01.979-.187.891.891 0 01.403.318.84.84 0 01-.112 1.09.917.917 0 01-.635.253z"
                                        fill="#333" />
                                </g>
                                <defs>
                                    <clipPath id="clip0">
                                        <path fill="#fff" d="M0 0h21v19H0z" />
                                    </clipPath>
                                </defs>
                            </svg>
                            <span class="ml-1">KERANJANG  @if(Auth::check()) ({{count(Auth::user()->cart)}}) @else() (0) @endif</span>
                        </a>
                    </li>
                    @if (Auth::check())
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('profile.index')}}">{{Auth::user()->name ?? Auth::user()->email}}</a>
                    </li>
                    @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('login.email')}}">MASUK</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('register.email')}}">DAFTAR</a>
                    </li>
                    @endif
                </ul>
            </div>
        </nav>
    </div>
    <!-- end:/header top -->

    <!-- start:header main -->
    <div class="header__main">
        <div class="container">
            <nav class="header__main__box navbar navbar-expand-lg">
                <a class="navbar-brand" href="{{url('/')}}">
                    <img width="100" src="{{asset('assets/images/logo-color.svg')}}" alt="Logo Agres ID">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- start:menu -->
                    <ul class="navbar-nav mr-auto">
                        @foreach ($categories as $category)
                        <li class="nav-item">
                            <a class="nav-link" href="#">{{$category->name}}</a>
                        </li>
                        @endforeach
                        {{-- <li class="nav-item">
                            <a class="nav-link add-button" href="#">A2HS</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Bundling Office</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Laptop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">AIO & Desktop PC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">PC / Desktop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Printer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Software</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Aksesoris</a>
                        </li> --}}
                    </ul>
                    <!-- end:/menu -->

                    <!-- start:search -->
                    <div class="search">
                        <form method="POST">
                            <input type="text" class="form-control" placeholder="cari produk disini" autocomplete="off">
                            <button type="submit" class="btn">
                                <svg width="14" height="14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g clip-path="url(#clip0)">
                                        <path
                                            d="M13.915 13.09L9.848 9.023a5.553 5.553 0 10-.825.825l4.067 4.066a.295.295 0 00.413 0l.412-.412a.295.295 0 000-.412zM5.542 9.916a4.375 4.375 0 110-8.75 4.375 4.375 0 010 8.75z"
                                            fill="#333" />
                                    </g>
                                    <defs>
                                        <clipPath id="clip0">
                                            <path fill="#fff" d="M0 0h14v14H0z" />
                                        </clipPath>
                                    </defs>
                                </svg>
                            </button>
                        </form>
                    </div>
                    <!-- end:/search -->
                </div>
            </nav>
        </div>
    </div>
    <!-- end:/header main -->
</header>
<!-- end:/header -->

engine/resources/views/layouts/loading.blade.php
<style>
    @keyframes flickerAnimation {
        0% {
            opacity: 1;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }

    @-o-keyframes flickerAnimation {
        0% {
            opacity: 1;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }

    @-moz-keyframes flickerAnimation {
        0% {
            opacity: 1;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }

    @-webkit-keyframes flickerAnimation {
        0% {
            opacity: 1;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }
    .animate-flicker {
        -webkit-animation: flickerAnimation 1s infinite;
        -moz-animation: flickerAnimation 1s infinite;
        -o-animation: flickerAnimation 1s infinite;
        animation: flickerAnimation 1s infinite;
    }
</style>

<div class="row no-gutters" id="loadingShow">
    <div class="col-12 w-100 h-100" style="position: fixed; top:0px; background-color: #fff; z-index:1001">
        <img class="animate-flicker" src="{{asset("assets/images/logo-color.svg")}}" alt=""
            style="position: absolute;right: 48%;top: 47%;">
    </div>
</div>

engine/resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    {{-- <a href="{{ route('dashboard') }}"> --}}
                        <a href="#">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                {{-- <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div> --}}
            </div>

            <!-- Settings Dropdown -->
            {{-- <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>Test</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Logout') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div> --}}

            <!-- Hamburger -->
            {{-- <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div> --}}
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        {{-- <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div> --}}

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    {{-- <div class="font-medium text-base text-gray-800">{{ auth('api')->user()->name }}</div> --}}
                    {{-- <div class="font-medium text-sm text-gray-500">{{ auth('api')->user()->email }}</div> --}}
                </div>
            </div>
{{--
            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Logout') }}
                    </x-responsive-nav-link>
                </form>
            </div> --}}
        </div>
    </div>
</nav>